### ISSUE TITLE
Amazing with a little problem

### ISSUE THREAD

**Issue by FranJNS** [Fidifis/Channel-packing#1]
Hi Fidelis. Your conversor is incredible. I have wasted too time in this manual fountion in Affinity, but it don't export alpha channel. I was crazy about this unwished result. I have searched a solution for months to this moment that I found your work. Thank you very much. However, how can I pack RGB+Alpha, for example a Normal Map with a Displacement Map? 

I edit the message for comunicate a second issue, because channel packing transform the original 16 bits bits by individual channels in 8 bit dephtmap by channel. Sometimes is usefull preserve it.

Thank you very much for your attention.

**Comment by fidifis** [comment]
Hi FranJNS,
I'm so glad you like my work. If you want to add an alpha channel to the normal map, simply load the normal map into each RGB channel and then load the Displacement to alpha channel and that's it. I hope that it helped you.

Support for 16-bit images has not yet been implemented. The program should throw an exception when processing unsupported formats, but it seems to mysteriously convert them to 8-bit.

Thank you for your report, have a nice day.

**Comment by fidifis** [comment]
16-bit image processing is now supported in the new project.
[https://github.com/Fidifis/TextureMerge](https://github.com/Fidifis/TextureMerge)
